environment:
  name: ALE/Breakout-v5

preprocessing:
  enabled: true
  type: atari
  frame_stack_size: 4
  target_image_size: [84, 84]

agent:
  epsilon_start: 1.0
  epsilon_end: 0.1

replay_buffer:
  memory_capacity: 1000000
  mini_batch_size: 32

learning:
  gamma: 0.99
  learning_rate: 0.00025
  gradient_momentum: 0.95
  squared_gradient_momentum: 0.95
  min_squared_gradient: 0.01

training:
  num_episodes: 800