environment:
  name: ALE/Breakout-v5

preprocessing:
  enabled: true
  type: atari
  frame_stack_size: 4
  target_image_size: [84, 84]

agent:
  epsilon: 1.0

replay_buffer:
  mini_batch_size: 32

learning:
  gamma: 0.99